### ISSUE TITLE
Error on Ext.Viewport.getController().onLaunch();

### ISSUE THREAD

**Issue by manelj** [sencha-extjs-examples/Coworkee#12]
Hello, i'm trying to run your example in Extjs 6.2.0 GPL
I have commented all listswipe code and now i can build correct the app.
But when i try to test it, in browser the line Ext.Viewport.getController().onLaunch();  returns null in getController() (file Application.js)

Anyone can help me to solve this?

**Comment by gportela85** [comment]
The whole app expects the functionality in 6.5.x to be available in order to work. None of the pages will render correctly using ExtJS 6.2.
