### ISSUE TITLE
Coworkee is hanging outside of localhost

### ISSUE THREAD

**Issue by vadymf** [sencha-extjs-examples/Coworkee#5]
I've followed all the steps for the initial installation and launch outlined at https://github.com/sencha-extjs-examples/Coworkee
The app runs normally locally. However, it hangs indefinitely past the login page when accessed outside of localhost by DNS or IP address. The initial screen gets displayed just fine but a click on the LOG IN > button brings it into a spinning mode for good. This is not a browser issue as the behavior is reproducible using IE and Chrome. The firewall is disabled on the host running the web server. Please advise.

**Comment by simonbrunel** [comment]
@vadymf did you change the Ext.Direct [`server`](/sencha-extjs-examples/Coworkee/blob/master/server/config.json#L16) config to use the name/IP of your server?

**Comment by vadymf** [comment]
Thanks for your response, Simon! I've started off with the default of "localhost" then tried both the machine name and IP. When I switch to either machine name or IP address, I can't log in even locally. Is it something pretty obvious I'm missing?

**Comment by simonbrunel** [comment]
Is there any messages in the browser console? If you can see the login form but it fails to login, that could be a CORS issue. For example, if your server IP is 192.168.1.2 (and so you changed the [`direct.server`](sencha-extjs-examples/Coworkee/blob/master/server/config.json#L16) config with that address), it will fail to log in if you try to access the app via https://localhost:3000 (or https://127.0.0.1:3000). You need to use http://192.168.1.2:3000.

Alternatively, you can enable CORS by setting [`cors.enabled: true`](sencha-extjs-examples/Coworkee/blob/master/server/config.json#L3)

**Comment by vadymf** [comment]
Ahh, that was it, the 3000 port to access the app at the IP address! Now it finally seems accessible from outside of the localhost. Many thanks for bearing with me!
