### ISSUE TITLE
Could you pls. give hints how to run client on ExtJS6.2 ?

### ISSUE THREAD

**Issue by zanzara** [sencha-extjs-examples/Coworkee#6]
Unfortunately I got only ExtJs6.2 (as GPL)  and your sophisticated example uses compoments which are not available under 6.2.  
So `sencha app build` will fail.
Could you pls. give an example which is compatible with ExtJS6.2 ? 
Or least could you give some hints, where the newer components of 6.5 are used 
(and maybe could be exchanged or commented out)?

Thanks  a lot in advance.
BR

**Comment by manelj** [comment]
I have the same problem, with extjs 6.2.0 gpl
Sencha app build returns:
[ERR] BUILD FAILED
[ERR] C:\Coworkee\client\build.xml:4: Cannot find C:\Users\USUARI\bin\Sencha\Cmd
\6.2.0.103\ant\build\app\build-impl.xml imported from C:\Coworkee\client\build.x
ml

**Comment by manelj** [comment]
You have to comment all listswipe references in phone views, sass, etc.

**Comment by gportela85** [comment]
The app is currently not support with 6.2, it was written for 6.5+ and the views will not work with older versions.
